### ISSUE TITLE
`pkg_resources` warnings on install

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/humbug#98]
```
<redacted>/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```

```
<redacted>/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
```

**Comment by zomglings** [comment]
`packages_report` uses `pkg_resources` to view the installed packages. It is causing problems now in Python environments that don't have working `setuptools` module.;

Offending line of code: https://github.com/bugout-dev/humbug/blob/main/python/humbug/report.py#L336

Problem with environment: https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

The fix is to either remove `packages_report` or make it noop if `pkg_resources` was not successfully imported.

**Comment by Andrei-Dolgolev** [comment]
resolve https://github.com/bugout-dev/humbug/pull/99
